apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-rollout
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 30
        - pause: {}
        - setWeight: 50
        - pause: { duration: 30 }
        - setWeight: 100
  selector:
    matchLabels:
      app: web-rollout
  template:
    metadata:
      labels:
        app: web-rollout
    spec:
      containers:
        - name: web
          image: showrav13/kube-app:v1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-rollout
spec:
  type: LoadBalancer
  selector:
    app: web-rollout
  ports:
    - port: 80
      targetPort: 3000
